### ISSUE TITLE
Not detecting changes in orientation

### ISSUE THREAD

**Issue by johnohara** [WickyNilliams/enquire.js#117]
I've been testing the latest version 2.1.2.

Queries work on my desktop - triggered by browser resize but do not trigger upon change in orientation on my phone (HTC mini 1).

The queries are triggered correctly for the first time - if I type in the url when in landscape, I get landscape, and the same in portrait. Native media queries also work correctly on orientation change.

**Comment by WickyNilliams** [comment]
Yeah, I'm not seeing issues either. Closing
