### ISSUE TITLE
No event when changing from desktop to tablet

### ISSUE THREAD

**Issue by binarykitchen** [WickyNilliams/enquire.js#119]
It looks like `match()` is never called when I resize the window from desktop down to tablet. This is my configuration:

``` js
enquire.register("all and (min-width: 980px)"), {
    match: function() {
        // Code for desktop
    }
});

enquire.register("all and (min-width: 650px)"), {
    match: function() {
       // Code for tablets 
    }
});

enquire.register("all and (max-width: 649px)"), {
    match: function() {
       // Code for mobile 
    }
});
```

When I resize from i.E. `1000px` to `700px`, the tablet handler is never called. But when I resize from `200px` for mobile to `700px`, then the tablet handler is called. Weird. Any ideas why?

**Comment by WickyNilliams** [comment]
I'm cleaning up old issues. I'm going to delete this as I assume it's no longer an issue. If the problem still persists, please comment here.
