### ISSUE TITLE
reload method

### ISSUE THREAD

**Issue by rkgrep** [WickyNilliams/enquire.js#121]
If some layout is changed by enquire and then content is reloaded (e.g. with ajax) there should be some reload method to run matching rules again.
Example code:

    enquire.register('some query',{
        match: function() { $('#my-id .my-class').addClass('another-class-1'); },
        unmatch: function() { $('#my-id .my-class').addClass('another-class-2'); }
    });
    $('#my-id').load('/ajax-url', function(){ enquire.reload(); });

At the moment after ajax loading we dont have neither .another-class-1 or .another-class-2 on loaded elements

**Comment by whoever123** [comment]
Are you trying to load different content into the same section based on size?  I'm trying to do something similar.  It seems setup/defer won't work in this case.

I haven't started using it yet, but can't you just do math: loadA and unmatch loadB?
