### ISSUE TITLE
Add Licence file to the project

### ISSUE THREAD

**Issue by jmburnz** [WickyNilliams/enquire.js#126]
I am using enquire in a Drupal theme and for Drupal 8 we are encouraged to link to a projects licence when we use 3rd party scripts. It would be most helpful if the MIT licence could be added to the repo and filled out appropriately.

**Comment by WickyNilliams** [comment]
Oh shit, I can't believe I missed this! Will add

**Comment by WickyNilliams** [comment]
Done
