### ISSUE TITLE
shouldDegrade isn't firing match function in IE8

### ISSUE THREAD

**Issue by dwilt** [WickyNilliams/enquire.js#132]
Similar to this issue: https://github.com/WickyNilliams/enquire.js/issues/14

I'm trying to match a desktop experience for IE8. I'm actually looking at the [should-degrade](http://wicky.nillia.ms/enquire.js/examples/should-degrade/) page on your site and it doesn't seem to be working there either (if I'm understanding the example it should say match because I'm in IE8, right?). See this screenshot: https://www.dropbox.com/s/vxbdazf8wwduxfx/Screenshot%202015-02-26%2019.27.05.png?dl=0

Here's my code (**note:** true is being passed as the 3rd parameter for shouldDegrade):

```
(function($, window, document, undefined) {

    $(function() {

         enquire.register('(min-width: 768px)', {
                match: function() {
                    console.log('this fires on modern browsers and with IE9 and the matchMedia polyfill but not in IE8');
                }
            }, true);

    });

})(jQuery, window, document);
```

I'd be willing to do a screenshare or something with you to show you the problem. If you're interested, let me know and I'll send you a join.me invite.

Thanks!

**Comment by WickyNilliams** [comment]
Closing this to clean up issues. Please respond if the problem still persists
