### ISSUE TITLE
Make enquire available on NPM

### ISSUE THREAD

**Issue by dbeff** [WickyNilliams/enquire.js#136]
I see enquire.js is already a UMD module. Is there any plans for uploading to NPM?

**Comment by rakowski91** [comment]
+1. That'd be awesome.

**Comment by conor** [comment]
:+1:

**Comment by jorrit** [comment]
:+1:

**Comment by michaelBenin** [comment]
https://www.npmjs.com/package/enquire.js

**Comment by jorrit** [comment]
Thanks for that link. It is hard to find, the package named `enquire` comes up first. Also, the package is one version behind.

**Comment by WickyNilliams** [comment]
The npm package is no longer behind. Excuse the delay :P
