### ISSUE TITLE
Media print

### ISSUE THREAD

**Issue by Mziserman** [WickyNilliams/enquire.js#137]
Hi.

I wanted to use your nice program to help me print a slider.
It's great because it takes the slides and can append them in another div where they will be visible. And also can hide the basic slider.

The problem is, when I print, it only gets the first page (on which there is two slides). I think it's an issue of timing but i'm not sure.

My code : 

```
enquire.register('print', {
    match: function(){
        var slides = $('.slide')
        slides.each(function(index, element){
            $("#printContainer").append(element)
        });
        $('.slider').css('display', 'none')
    }
})
```

**Comment by WickyNilliams** [comment]
Could you whip up a fiddle or something of the sort to demo the issue?

**Comment by WickyNilliams** [comment]
Closing to clean up issues. Please comment here if you are still having this problem
