### ISSUE TITLE
How to change variable in <script src="">

### ISSUE THREAD

**Issue by asker-hr** [WickyNilliams/enquire.js#140]
Hi,
do you have idea how to change value of one variable depends on browser screen and append it to src paramater in html?

var calendar = 2;
enquire.register("screen and (max-width:768px)", {
    match : function() { calendar = 1;  },      
    unmatch : function() {    calendar = 3;},    

});

<script type="text/javascript" src="index.php?view=CALENDAR-VALUE-HERE"></script>

any help?

**Comment by WickyNilliams** [comment]
I'm closing personal help requests so I can get through the backlog of issues. These type of questions are more suited to StackOverflow.
