### ISSUE TITLE
Enquire js exception while using Savvior

### ISSUE THREAD

**Issue by ev5unleash** [WickyNilliams/enquire.js#142]
Hey there,

I'm not sure if this is an issue with how Savvior is using Enquire, or if it's an actual issue with Enquire, but here's my issue. 

I'm dynamically loading in div's that I wish to attach savvior to. After I load in the div I use the code:

savvior.init('#cards', {
"screen and (max-width: 20em)": { columns: 2 },
"screen and (min-width: 20em) and (max-width: 40em)": { columns: 2 },
"screen and (min-width: 40em)": { columns: 2 },
});

When I'm about to unload this content I call, "savvior.destroy();". However, when I call this function, an exception from enquire comes up saying "TypeError: this.msql.removeListener is not a function.". I double checked my work to make sure I wasn't destroying the actual div I've attached Savvior to and still getting the same thing.

EDIT: It seems to have to do with the function unregister in Enquire. Full error: TypeError: this.mql.removeListener is not a function at Object.f.clear (enquire.min.js:7:1559) at Object.g.unregister (enquire.min.js:7:1998) at savvior.min.js:6:5278 at c (savvior.min.js:6:365) at g.unregister (savvior.min.js:6:5243) at null.<anonymous> (savvior.min.js:6:6252) at c (savvior.min.js:6:365) at h.destroy (savvior.min.js:6:6207) at HTMLDivElement.<anonymous> (page.js:33:21) at HTMLDivElement.d (https://code.jquery.com/jquery-2.1.1.min.js:3:10897)

Thanks,

**Comment by WickyNilliams** [comment]
This will be fixed with #124

**Comment by WickyNilliams** [comment]
Should now be fixed in `v2.1.4`
