### ISSUE TITLE
Enquire, mediaMatch support, Respond & IE 8

### ISSUE THREAD

**Issue by monolux** [WickyNilliams/enquire.js#145]
The past 10 minutes I was trying to get Enquire working on IE8 alongside [media-match](https://github.com/weblinc/media-match) and [Respond](https://github.com/scottjehl/Respond). Here is my solution if other people are having trouble.

Only after reading through "[Support & Caveats](https://github.com/scottjehl/Respond#support--caveats)" I got to understand that if you already have a mediaMatch polyfill in place you will not need Respond if you are also using Enquire. At least this is what made it work here.

> Browsers that natively support CSS3 Media Queries are opted-out of running this script as quickly as possible. In testing for support, all other browsers are subjected to a quick test to determine whether they support media queries or not before proceeding to run the script. This test is now included separately at the top, and uses the window.matchMedia polyfill found here: https://github.com/paulirish/matchMedia.js . If you are already including this polyfill via Modernizr or otherwise, feel free to remove that part.

I had Respond, media-match and Enquire loading and that gave me the following error.

> Message: Object doesn't support this property or method
> Line: 7
> Char: 572
> Code: 0
> URI: http://work.webdev/Domain/js/vendor/enquire.2.1.2.min.js

**Be removing Respond it started to work flawless with media-match and Enquire.**
By removing media-match **and** and leaving Respond **and** Enquire it did not work and gave me above error.

Heads up!

**Comment by WickyNilliams** [comment]
This issue has popped up many times. It is because Respond includes it's own polyfill for matchMedia, which clashes with any other polyfill for matchMedia (e.g. media-match as you are using). You should edit Respond and remove the polyfill from the top of the file (the Respond docs mention this).

**Comment by monolux** [comment]
Here things work completely without Respond native IE8 upwards. So media-match and Enquire are all it basically takes. Or would you suggest still using Respond with the removed polyfill alongside Enquire and the standalone media-match polyfill?
