### ISSUE TITLE
Display Current Media Query

### ISSUE THREAD

**Issue by monolux** [WickyNilliams/enquire.js#146]
Hi Nick, trying to display the current media query on the page. [reference](https://stackoverflow.com/questions/36241255/enquirejs-display-current-media-query)

Perhaps you could help out or point in the right direction?

Just learning all this and during development it would help me super lots to have a simple div with the current media query range displayed, e.g. appended to the body.

**Comment by WickyNilliams** [comment]
You could create a simple helper function, which wraps your listener object and adds/removes an element from the DOM on match/unmatch. Something like this: https://jsfiddle.net/e1agyhtn/

**Comment by monolux** [comment]
Been pullig my hair and will learn tons from your fiddle. Thank you so much!!
