### ISSUE TITLE
Enquire.js and Vue.js, odd behavior

### ISSUE THREAD

**Issue by pierrebonbon** [WickyNilliams/enquire.js#147]
I'm doing media queries with _Enquire.js_ and _Vue.js_. It all pretty much works when I resize the browser's window manually. However, nothing happens when switching _Chrome's toggle device mode_ on or when accessing the site on a mobile phone. I checked with the "Match & Unmatch Example", and it works as expected in the said mode. I wonder if there's some sort of incompatibility between _Vue.js_ and _Enquire.js_ or am I doing something wrong?

The logic for the media queries is on my vue instance's [_ready_][n1] hook:

    ready:

        function () {

            var self = this;

            window.addEventListener("resize",
                enquire.register("screen and (max-width: 800px)", {
                    match: function () {
                        self.displayIsLarge = false;
                        self.displayIsSmall = true;
                    },
                    unmatch: function () {
                        self.displayIsLarge = true;
                        self.displayIsSmall = false;
                    }
                })
            );

On my vue instance, I've the following data propperties:

    var menu = new Vue({
    el: '#app',
    data: {
        displayIsLarge: true,
        displayIsSmall: false,

On my html file, I'm using `v-if="displayIsSmall"` and `v-if="displayIsLarge"` to hide/display elements according to the browser's size.  

Snapshots of [large][n2] and [small][n3] browser window firing expected behavior. Snapshot with [Chrome toggle device mode on][n4], not firing expected behavior.

[n1]: http://vuejs.org/api/#ready
[n2]: https://gyazo.com/6e2dd8a5ec2f7bb7a323420ca4ed11a1
[n3]: https://gyazo.com/75e66e924b73ba2aa51050e756d569a2
[n4]: https://gyazo.com/429b87780886635f03caead5f4e7f1d7

**Comment by pierrebonbon** [comment]
The `resize` event handler is altogether superfluous. For a moment I thought it could even be the culprit. Unfortunately, calling `enquire.register` directly doesn't seem to change this annoying behavior. Here's a Jsfiddle [with][n1] and [without][n2] the window `resize` handle. 

[n1]: http://jsfiddle.net/932fu9ox/12/
[n2]: https://jsfiddle.net/932fu9ox/14/

**Comment by pierrebonbon** [comment]
No luck either with the `beforeCompile` hook and Enquire's `setup` callback:

     setup: function() {
                    self.displayIsSmall = this.match;
                    self.displayIsLarge = this.unmatch;
                },

JsFiddle [here](http://jsfiddle.net/pierrebonbon/932fu9ox/20/)

**Comment by pierrebonbon** [comment]
[solved](http://stackoverflow.com/questions/36335392/enquire-js-does-not-match-initially-only-on-resize/36343837#36343837)

**Comment by WickyNilliams** [comment]
Good to hear! Enquire was designed with mobile first in mind, hence why unmatch only fires if match has previously fired. You should set sensible defaults for mobile, change them in a match for larger viewports, and then undo the changes in unmatch

Will close this issue

**Comment by pierrebonbon** [comment]
Thanks for the clarification! Had no idea about it before coming upon this issue. I wonder if it wouldn't be better to add this piece of information to the documentation?

**Comment by WickyNilliams** [comment]
It is covered in the docs :)

> Unmatch: If supplied, triggered when the media query transitions **from a matched state to an unmatched state**

**Comment by pierrebonbon** [comment]
Ohh, I'm so dumm! My apologies!

**Comment by WickyNilliams** [comment]
You're not the first person to make this mistake, and i'm sure you won't be the last :) Don't worry

**Comment by pierrebonbon** [comment]
:-)  Btw, thanks for the great library!
