### ISSUE TITLE
Unit tests for registered media query callbacks.

### ISSUE THREAD

**Issue by vishnurk** [WickyNilliams/enquire.js#149]
Is there a way to trigger(invoke) registered media query callbacks via JS unit tests? 

I have multiple media queries / callbacks registered with 'enquire' and I am looking for a way to trigger the registered callbacks to meet unit testing requirements.

**Comment by WickyNilliams** [comment]
Something like `enquire.queries[yourMediaQuery].asses()`?

In any case, I'm closing this to clean up issues. Please comment here if you're still having problems
