### ISSUE TITLE
Playing nice with Foundation 6 Framework

### ISSUE THREAD

**Issue by shannonschaerer** [WickyNilliams/enquire.js#150]
For the life of me I can't get enquire to work with the Foundation Framework. I've installed it with bower, and I also tried manually, but I all I end up with is an Uncaught TypeError: Cannot set property 'enquire' of undefined. Does anyone know what this might be and how I can solve it?

**Comment by sachya** [comment]
do you have some code to show?

**Comment by WickyNilliams** [comment]
Closing this to clean up issues. Please comment here if you're still having issues
