### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by tjezierski** [WickyNilliams/enquire.js#153]
Hi, I'm kind a newbie in jQ and JS and for a whole day I was trying to figure it out, why my code is not working. Im trying to achieve effect when on desktop I have a fadding in horizontal menu (on scroll) and for mobile there is no such effect. So depends on screen width I activating or deactivating this element with effect, please give me a guide what am I doing wrong:

```
function mediaQuery(){

    enquire.register("screen and (min-width: 960px)", {
        match: function headerFadeIn() {

            $(window).scroll(function () {
                if ($(this).scrollTop() > 150){
                        $('.desktop__menu--fadein').fadeIn(500);
                        $('.desktop__menu--fadein').css('display','flex');
                    } else {
                        $('.desktop__menu--fadein').fadeOut(500);
                    }
        });
    },
        unmatch: function headerFadeIn() {
            $('.desktop__menu--fadein').css({'display':'none'});
        }
    });
}
```

**Comment by jameelmoses** [comment]
You're declaring a function, but you're not calling the function. Move you function declaration outside of the enquire block, and then call the named functions inside of it instead of declaring them there. For example `match: headerFadeIn();`

**Comment by jameelmoses** [comment]
`enquire.register("screen and (min-width: 960px)", {
  match: function() {
    $(window).scroll(function() {
      if ($(this).scrollTop() > 150) {
        $('.desktop__menu--fadein').fadeIn(500);
        $('.desktop__menu--fadein').css('display', 'flex');
      } else {
        $('.desktop__menu--fadein').fadeOut(500);
      }
    });
  },
  unmatch: function() {
    $('.desktop__menu--fadein').css({
      'display': 'none'
    });
  }
});`

**Comment by jameelmoses** [comment]
```javascript
enquire.register("screen and (min-width: 960px)", {
  match: function() {
    $(window).scroll(function() {
      if ($(this).scrollTop() > 150) {
        $('.desktop__menu--fadein').fadeIn(500);
        $('.desktop__menu--fadein').css('display', 'flex');
      } else {
        $('.desktop__menu--fadein').fadeOut(500);
      }
    });
  },
  unmatch: function() {
    $('.desktop__menu--fadein').css({
      'display': 'none'
    });
  }
});
```

**Comment by WickyNilliams** [comment]
In order to clean up issues, i'm closing old issues. Please comment if you still have this problem
