### ISSUE TITLE
Newest version on npm

### ISSUE THREAD

**Issue by kenborge** [WickyNilliams/enquire.js#155]
It doesn't seem like the newest version is published on npm
https://www.npmjs.com/package/enquire.js 2.1.1 is the newest there

**Comment by isellsoap** [comment]
@WickyNilliams Is this repository still maintained?

**Comment by WickyNilliams** [comment]
Yes, still maintained, just badly :P I will be looking for maintainers to help me in near future. I will publish the latest version today or tomorrow.

**Comment by WickyNilliams** [comment]
`v2.1.4` is now available on npm
