### ISSUE TITLE
trigger when page loaded first time

### ISSUE THREAD

**Issue by erlangparasu** [WickyNilliams/enquire.js#168]
trigger when page loaded first time

**Comment by erlangp** [comment]
ow sorry i just add min-width at that is work.. peace

    enquire.register('screen and (min-width: 1025px)', {
        match: function () {
            console.log('enquire', 'match:', '1025px');
        },
        unmatch: function () {
            console.log('enquire', 'unmatch:', '1025px');
        },
        setup: function () {
            console.log('enquire', 'setup:', '1025px');
        },
        deferSetup: true,
        destroy: function () {
            console.log('enquire', 'destroy:', '1025px');
        }
    });
