### ISSUE TITLE
Responsive images

### ISSUE THREAD

**Issue by moargh** [WickyNilliams/enquire.js#24]
I stumbled upon your library on CSS Tricks where you mentioned that it’s possible to switch an image’s src depending on which media query matches by using data-\* attributes. Do you have a working example how to use this feature? I couldn’t find anything on your demo page.

**Comment by iaminawe** [comment]
I would also like to know the answer to @mariusooms question as I have three image urls I need to switch between. Thanks for any help you can offer.
