### ISSUE TITLE
Different match and unmatch orders  

### ISSUE THREAD

**Issue by mjlescano** [WickyNilliams/enquire.js#38]
Match and unmatch functions are triggered in different order when going smaller than going big.
I made this fiddle to compensate my rusty english
http://jsfiddle.net/mjlescano/FmmTa/3/embedded/result/

Tested resizing the window,

**reducing the window width the triggers are:**
match:bigger
unmatch:bigger
match:normal

**making bigger the window, triggers:**
match:normal
match:bigger
unmatch:normal

**It should be**
match:normal
unmatch:normal
match:bigger

**Comment by verrasse** [comment]
This is not a browser bug. It follows the specifications. Javascript event queue is a simple **FIFO**, first registered — first fired. If you register **event A** and then register **event B**, it will guarantied that **A** will always run before **B** on a compliant browser.
