### ISSUE TITLE
bower version and tag mismatch

### ISSUE THREAD

**Issue by codekipple** [WickyNilliams/enquire.js#78]
Just installed via bower to the latest tag v2.1.0 and bower said this:-
"mismatch Version declared in the json (2.0.3) is different than the resolved one (2.1.0)"

**Comment by Shedal** [comment]
This is again an issue. All versions from 2.1.3 and above have 2.1.2 specified in the package.json:

https://github.com/WickyNilliams/enquire.js/blob/v2.1.6/bower.json
