### ISSUE TITLE
should-degrade should degrade

### ISSUE THREAD

**Issue by szepeviktor** [WickyNilliams/enquire.js#94]
Please use jQuery on this page, e.g. Zepto does not support IE8.
http://wicky.nillia.ms/enquire.js/examples/should-degrade/

**Comment by WickyNilliams** [comment]
This may have taken me 3 years, but I'm close to updating the docs to fix this. Thanks for your (extreme) patience 😆

**Comment by jpsc** [comment]
@WickyNilliams need any help with the docs ? Is there a branch ?
