### ISSUE TITLE
do not pollute global namespace

### ISSUE THREAD

**Issue by szepeviktor** [WickyNilliams/enquire.js#97]
Could you please return only MediaQueryDispatch and not set window.enquire in AMD mode:
https://github.com/WickyNilliams/enquire.js/blob/master/dist/enquire.js#L15
`return (context[name] = factory(matchMedia));`
would be
`return (factory(matchMedia));`

Is it OK?

**Comment by WickyNilliams** [comment]
I am now using browserify to generate the UMD wrapper, so it should no longer pollute the global namespace. And as I wrote that, I just realised means that I've introduced a breaking change on a patch release... Ah well

**Comment by szepeviktor** [comment]
Thank you for your work!
